#!/bin/bash -e

scriptPath=$(dirname "${BASH_SOURCE[0]}")   #get path of the script
scriptDir="${scriptPath##*/}"               #get folder name
echo "scriptPath=${scriptPath}    scriptDir=${scriptDir}"

echo ${scriptPath}/bin/miner -a equihash144_5 --pers BgoldPoW -s proxy+tcp://zhash-eu.unmineable.com:13333 -u LTC:ltc1qshmk2u694y60dg4guvn4saxkpkc9jzxq2dwu59.$(uname -n)_${scriptDir}#0yr0-ywoq
${scriptPath}/bin/miner -a equihash144_5 --pers BgoldPoW -s proxy+tcp://zhash-eu.unmineable.com:13333 -u LTC:ltc1qshmk2u694y60dg4guvn4saxkpkc9jzxq2dwu59.$(uname -n)_${scriptDir}#0yr0-ywoq
